/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddToCartRequest,
  UpdateCartItemParams
} from '../generated.schemas';




  export const getShoppingCartController = (axiosInstance: AxiosInstance = axios.default) => {
const updateCartItem = (
    productId: number,
    params: UpdateCartItemParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.put(
      `/api/cart/items/${productId}`,undefined,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const removeFromCart = (
    productId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.delete(
      `/api/cart/items/${productId}`,{
        responseType: 'blob',
    ...options,}
    );
  }
const addToCart = (
    addToCartRequest: AddToCartRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.post(
      `/api/cart/items`,
      addToCartRequest,{
        responseType: 'blob',
    ...options,}
    );
  }
const getCart = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/cart`,{
        responseType: 'blob',
    ...options,}
    );
  }
return {updateCartItem,removeFromCart,addToCart,getCart}};
export type UpdateCartItemResult = AxiosResponse<Blob>
export type RemoveFromCartResult = AxiosResponse<Blob>
export type AddToCartResult = AxiosResponse<Blob>
export type GetCartResult = AxiosResponse<Blob>
