/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddToCartRequest,
  CartResponse,
  UpdateCartItemParams
} from '../generated.schemas';




  export const getShoppingCartController = () => {
const updateCartItem = <TData = AxiosResponse<CartResponse>>(
    productId: number,
    params: UpdateCartItemParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/cart/items/${productId}`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const removeFromCart = <TData = AxiosResponse<CartResponse>>(
    productId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/cart/items/${productId}`,options
    );
  }
const addToCart = <TData = AxiosResponse<CartResponse>>(
    addToCartRequest: AddToCartRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/cart/items`,
      addToCartRequest,options
    );
  }
const getCart = <TData = AxiosResponse<CartResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/cart`,options
    );
  }
return {updateCartItem,removeFromCart,addToCart,getCart}};
export type UpdateCartItemResult = AxiosResponse<CartResponse>
export type RemoveFromCartResult = AxiosResponse<CartResponse>
export type AddToCartResult = AxiosResponse<CartResponse>
export type GetCartResult = AxiosResponse<CartResponse>
