/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetRecentOrdersParams
} from '../generated.schemas';




  export const getStoreController = (axiosInstance: AxiosInstance = axios.default) => {
const getAllStores = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/stores`,{
        responseType: 'blob',
    ...options,}
    );
  }
const getStoreById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/stores/${id}`,{
        responseType: 'blob',
    ...options,}
    );
  }
const getStoreStats = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/stores/stats`,{
        responseType: 'blob',
    ...options,}
    );
  }
const getRecentOrders = (
    params?: GetRecentOrdersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/stores/orders/recent`,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getAllStores,getStoreById,getStoreStats,getRecentOrders}};
export type GetAllStoresResult = AxiosResponse<Blob>
export type GetStoreByIdResult = AxiosResponse<Blob>
export type GetStoreStatsResult = AxiosResponse<Blob>
export type GetRecentOrdersResult = AxiosResponse<Blob>
