/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetRecentOrdersParams,
  OrderResponse,
  StoreResponse,
  StoreStatsResponse
} from '../generated.schemas';




  export const getStoreController = () => {
const getAllStores = <TData = AxiosResponse<StoreResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/stores`,options
    );
  }
const getStoreById = <TData = AxiosResponse<StoreResponse>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/stores/${id}`,options
    );
  }
const getStoreStats = <TData = AxiosResponse<StoreStatsResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/stores/stats`,options
    );
  }
const getRecentOrders = <TData = AxiosResponse<OrderResponse[]>>(
    params?: GetRecentOrdersParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/stores/orders/recent`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getAllStores,getStoreById,getStoreStats,getRecentOrders}};
export type GetAllStoresResult = AxiosResponse<StoreResponse[]>
export type GetStoreByIdResult = AxiosResponse<StoreResponse>
export type GetStoreStatsResult = AxiosResponse<StoreStatsResponse>
export type GetRecentOrdersResult = AxiosResponse<OrderResponse[]>
