/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CustomerStatsResponse
} from '../generated.schemas';




  export const getCustomerController = () => {
const getCustomerStats = <TData = AxiosResponse<CustomerStatsResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/customers/stats`,options
    );
  }
return {getCustomerStats}};
export type GetCustomerStatsResult = AxiosResponse<CustomerStatsResponse>
