/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';




  export const getCustomerController = (axiosInstance: AxiosInstance = axios.default) => {
const getCustomerStats = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/customers/stats`,{
        responseType: 'blob',
    ...options,}
    );
  }
return {getCustomerStats}};
export type GetCustomerStatsResult = AxiosResponse<Blob>
