/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
export interface AddProductRequest {
  /**
   * @minLength 0
   * @maxLength 200
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  type: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  brand: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description: string;
  /** @minimum 0.01 */
  price: number;
  /** @minimum 0 */
  stockQuantity: number;
}

export interface ProductResponse {
  id?: number;
  title?: string;
  type?: string;
  brand?: string;
  description?: string;
  price?: number;
  stockQuantity?: number;
  storeId?: number;
  storeName?: string;
}

export interface CartItemResponse {
  cartItemId?: number;
  productId?: number;
  productTitle?: string;
  productBrand?: string;
  productPrice?: number;
  quantity?: number;
  subtotal?: number;
  storeId?: number;
  storeName?: string;
  availableStock?: number;
}

export interface CartResponse {
  cartId?: number;
  items?: CartItemResponse[];
  totalPrice?: number;
}

export interface OrderItemResponse {
  orderItemId?: number;
  productId?: number;
  productTitle?: string;
  productBrand?: string;
  quantity?: number;
  priceAtPurchase?: number;
  subtotal?: number;
}

export interface OrderResponse {
  orderId?: number;
  customerId?: number;
  customerName?: string;
  storeId?: number;
  storeName?: string;
  totalPrice?: number;
  orderDate?: string;
  status?: string;
  items?: OrderItemResponse[];
}

export interface PaymentRequest {
  /**
   * @minLength 1
   * @pattern \d{16}
   */
  cardNumber: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  cardHolderName: string;
  /**
   * @minLength 1
   * @pattern (0[1-9]|1[0-2])/\d{2}
   */
  expiryDate: string;
  /**
   * @minLength 1
   * @pattern \d{3,4}
   */
  cvv: string;
}

export interface CheckoutResponse {
  paymentStatus?: string;
  transactionId?: string;
  message?: string;
  orders?: OrderResponse[];
}

export interface AddToCartRequest {
  productId: number;
  /** @minimum 1 */
  quantity: number;
}

export type RegisterRequestRole = typeof RegisterRequestRole[keyof typeof RegisterRequestRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterRequestRole = {
  STORE: 'STORE',
  CUSTOMER: 'CUSTOMER',
} as const;

export interface RegisterRequest {
  /**
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  email: string;
  /**
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  role: RegisterRequestRole;
  /**
   * @minLength 9
   * @maxLength 12
   */
  taxId?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  firstName?: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  lastName?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  storeName?: string;
  /**
   * @minLength 0
   * @maxLength 200
   */
  ownerName?: string;
}

export interface RegisterResponse {
  message?: string;
  username?: string;
  email?: string;
  role?: string;
}

export interface LoginRequest {
  /** @minLength 1 */
  username: string;
  /** @minLength 1 */
  password: string;
}

export interface LoginResponse {
  token?: string;
  type?: string;
  username?: string;
  email?: string;
  role?: string;
}

export interface UpdateProductStockRequest {
  /** @minimum 0 */
  stockQuantity: number;
}

export interface StoreResponse {
  id?: number;
  name?: string;
  owner?: string;
  productCount?: number;
}

export interface StoreStatsResponse {
  totalProducts?: number;
  productsInStock?: number;
  productsOutOfStock?: number;
  totalOrders?: number;
  totalOrdersCompleted?: number;
  uniqueCustomers?: number;
  totalRevenue?: number;
  totalItemsSold?: number;
}

export interface CustomerStatsResponse {
  itemsInCart?: number;
  cartTotalPrice?: number;
  totalOrders?: number;
  totalOrdersCompleted?: number;
  uniqueStoresPurchasedFrom?: number;
  totalAmountSpent?: number;
  totalItemsPurchased?: number;
}

export type UpdateCartItemParams = {
quantity: number;
};

export type GetProductsParams = {
title?: string;
type?: string;
brand?: string;
minPrice?: number;
maxPrice?: number;
storeId?: number;
};

export type GetRecentOrdersParams = {
limit?: number;
};

export type GetRecommendationsParams = {
limit?: number;
};

export type GetRecentOrders1Params = {
limit?: number;
};

