/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  RegisterRequest
} from '../generated.schemas';




  export const getAuthController = (axiosInstance: AxiosInstance = axios.default) => {
const register = (
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.post(
      `/api/auth/register`,
      registerRequest,{
        responseType: 'blob',
    ...options,}
    );
  }
const login = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.post(
      `/api/auth/login`,
      loginRequest,{
        responseType: 'blob',
    ...options,}
    );
  }
return {register,login}};
export type RegisterResult = AxiosResponse<Blob>
export type LoginResult = AxiosResponse<Blob>
