/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequest,
  LoginResponse,
  RegisterRequest,
  RegisterResponse
} from '../generated.schemas';




  export const getAuthController = () => {
const register = <TData = AxiosResponse<RegisterResponse>>(
    registerRequest: RegisterRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/register`,
      registerRequest,options
    );
  }
const login = <TData = AxiosResponse<LoginResponse>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/auth/login`,
      loginRequest,options
    );
  }
return {register,login}};
export type RegisterResult = AxiosResponse<RegisterResponse>
export type LoginResult = AxiosResponse<LoginResponse>
