/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CheckoutResponse,
  GetRecentOrders1Params,
  OrderResponse,
  PaymentRequest
} from '../generated.schemas';




  export const getOrderController = () => {
const getCustomerOrders = <TData = AxiosResponse<OrderResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders`,options
    );
  }
const completeOrder = <TData = AxiosResponse<OrderResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/orders`,undefined,options
    );
  }
const checkout = <TData = AxiosResponse<CheckoutResponse>>(
    paymentRequest: PaymentRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/orders/checkout`,
      paymentRequest,options
    );
  }
const getOrderById = <TData = AxiosResponse<OrderResponse>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders/${id}`,options
    );
  }
const getStoreOrders = <TData = AxiosResponse<OrderResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders/store`,options
    );
  }
const getRecentOrders1 = <TData = AxiosResponse<OrderResponse[]>>(
    params?: GetRecentOrders1Params, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/orders/recent`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getCustomerOrders,completeOrder,checkout,getOrderById,getStoreOrders,getRecentOrders1}};
export type GetCustomerOrdersResult = AxiosResponse<OrderResponse[]>
export type CompleteOrderResult = AxiosResponse<OrderResponse[]>
export type CheckoutResult = AxiosResponse<CheckoutResponse>
export type GetOrderByIdResult = AxiosResponse<OrderResponse>
export type GetStoreOrdersResult = AxiosResponse<OrderResponse[]>
export type GetRecentOrders1Result = AxiosResponse<OrderResponse[]>
