/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetRecentOrders1Params,
  PaymentRequest
} from '../generated.schemas';




  export const getOrderController = (axiosInstance: AxiosInstance = axios.default) => {
const getCustomerOrders = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/orders`,{
        responseType: 'blob',
    ...options,}
    );
  }
const completeOrder = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.post(
      `/api/orders`,undefined,{
        responseType: 'blob',
    ...options,}
    );
  }
const checkout = (
    paymentRequest: PaymentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.post(
      `/api/orders/checkout`,
      paymentRequest,{
        responseType: 'blob',
    ...options,}
    );
  }
const getOrderById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/orders/${id}`,{
        responseType: 'blob',
    ...options,}
    );
  }
const getStoreOrders = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/orders/store`,{
        responseType: 'blob',
    ...options,}
    );
  }
const getRecentOrders1 = (
    params?: GetRecentOrders1Params, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/orders/recent`,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getCustomerOrders,completeOrder,checkout,getOrderById,getStoreOrders,getRecentOrders1}};
export type GetCustomerOrdersResult = AxiosResponse<Blob>
export type CompleteOrderResult = AxiosResponse<Blob>
export type CheckoutResult = AxiosResponse<Blob>
export type GetOrderByIdResult = AxiosResponse<Blob>
export type GetStoreOrdersResult = AxiosResponse<Blob>
export type GetRecentOrders1Result = AxiosResponse<Blob>
