/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddProductRequest,
  GetProductsParams,
  GetRecommendationsParams,
  UpdateProductStockRequest
} from '../generated.schemas';




  export const getProductController = (axiosInstance: AxiosInstance = axios.default) => {
const getProductById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/products/${id}`,{
        responseType: 'blob',
    ...options,}
    );
  }
const updateProduct = (
    id: number,
    addProductRequest: AddProductRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.put(
      `/api/products/${id}`,
      addProductRequest,{
        responseType: 'blob',
    ...options,}
    );
  }
const deleteProduct = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/products/${id}`,options
    );
  }
const getProducts = (
    params?: GetProductsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/products`,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const addProduct = (
    addProductRequest: AddProductRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.post(
      `/api/products`,
      addProductRequest,{
        responseType: 'blob',
    ...options,}
    );
  }
const updateProductStock = (
    id: number,
    updateProductStockRequest: UpdateProductStockRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.patch(
      `/api/products/${id}/stock`,
      updateProductStockRequest,{
        responseType: 'blob',
    ...options,}
    );
  }
const getStoreProducts = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/products/store`,{
        responseType: 'blob',
    ...options,}
    );
  }
const getRecommendations = (
    params?: GetRecommendationsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    return axiosInstance.get(
      `/api/products/recommendations`,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getProductById,updateProduct,deleteProduct,getProducts,addProduct,updateProductStock,getStoreProducts,getRecommendations}};
export type GetProductByIdResult = AxiosResponse<Blob>
export type UpdateProductResult = AxiosResponse<Blob>
export type DeleteProductResult = AxiosResponse<void>
export type GetProductsResult = AxiosResponse<Blob>
export type AddProductResult = AxiosResponse<Blob>
export type UpdateProductStockResult = AxiosResponse<Blob>
export type GetStoreProductsResult = AxiosResponse<Blob>
export type GetRecommendationsResult = AxiosResponse<Blob>
