/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddProductRequest,
  GetProductsParams,
  GetRecommendationsParams,
  ProductResponse,
  UpdateProductStockRequest
} from '../generated.schemas';




  export const getProductController = () => {
const getProductById = <TData = AxiosResponse<ProductResponse>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/products/${id}`,options
    );
  }
const updateProduct = <TData = AxiosResponse<ProductResponse>>(
    id: number,
    addProductRequest: AddProductRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.put(
      `/api/products/${id}`,
      addProductRequest,options
    );
  }
const deleteProduct = <TData = AxiosResponse<void>>(
    id: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.delete(
      `/api/products/${id}`,options
    );
  }
const getProducts = <TData = AxiosResponse<ProductResponse[]>>(
    params?: GetProductsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/products`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
const addProduct = <TData = AxiosResponse<ProductResponse>>(
    addProductRequest: AddProductRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.post(
      `/api/products`,
      addProductRequest,options
    );
  }
const updateProductStock = <TData = AxiosResponse<ProductResponse>>(
    id: number,
    updateProductStockRequest: UpdateProductStockRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.patch(
      `/api/products/${id}/stock`,
      updateProductStockRequest,options
    );
  }
const getStoreProducts = <TData = AxiosResponse<ProductResponse[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/products/store`,options
    );
  }
const getRecommendations = <TData = AxiosResponse<ProductResponse[]>>(
    params?: GetRecommendationsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/api/products/recommendations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }
return {getProductById,updateProduct,deleteProduct,getProducts,addProduct,updateProductStock,getStoreProducts,getRecommendations}};
export type GetProductByIdResult = AxiosResponse<ProductResponse>
export type UpdateProductResult = AxiosResponse<ProductResponse>
export type DeleteProductResult = AxiosResponse<void>
export type GetProductsResult = AxiosResponse<ProductResponse[]>
export type AddProductResult = AxiosResponse<ProductResponse>
export type UpdateProductStockResult = AxiosResponse<ProductResponse>
export type GetStoreProductsResult = AxiosResponse<ProductResponse[]>
export type GetRecommendationsResult = AxiosResponse<ProductResponse[]>
